Pushed version to 3.1.3:  - Fixed a recipe serialization bug which was preventing people from joining servers, causing this to appear when attempting to join a server: java.lang.NoSuchMethodError: 'float com.oblivioussp.spartanweaponry.item.crafting.ITagCookingRecipe.m_43750_()'